# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - release/builds


#pr:
#  branches:
#    include:
#      - dev
#  paths:
#    exclude:
#      - version.sbt
variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Release
    displayName: Release Stage
    jobs:
      - job: ReleaseJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/var-release-ut.yml
        steps:
          - template: jobs/release.yml

  - stage: RollBackRelease
    displayName: RollBack Release Stage
    dependsOn: Release
    condition: failed('Release')
    jobs:
      - job: RollBackReleaseJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/var-release-ut.yml
        steps:
          - template: jobs/rollback.yml

#  - stage: UTStage
#    displayName: Deploy UT Stage
#    dependsOn: Release
#    condition: succeeded('Release')
#    jobs:
#      - deployment: DeploymentJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-ut.yml
#        environment: UT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
#  - stage: ITStage
#    displayName: Deploy IT Stage
#    dependsOn: UTStage
#    condition: succeeded('UTStage')
#    jobs:
#      - deployment: DeploymentITJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-it.yml
#        environment: IT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
#
#  - stage: UATStage
#    displayName: Deploy UAT Stage
#    dependsOn: ITStage
#    condition: succeeded('ITStage')
#    jobs:
#      - deployment: DeploymentUATJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-uat.yml
#        environment: UAT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml

  - stage: ProdStage
    displayName: Deploy Prod Stage
    dependsOn: UATStage
    condition: succeeded('UATStage')
    jobs:
      - deployment: DeploymentUATJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/var-deploy-prod.yml
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy-prod.yml