# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - dev

#pr:
#  branches:
#    include:
#      - dev
#  paths:
#    exclude:
#      - version.sbt
variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Release
    displayName: Release Stage
    jobs:
      - job: ReleaseJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/release.yml
        steps:
          - template: jobs/release.yml

  - stage: RollBackRelease
    displayName: RollBack Release Stage
    dependsOn: Release
    condition: failed('Release')
    jobs:
      - job: RollBackReleaseJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/release.yml
        steps:
          - template: jobs/rollback.yml

  - stage: DeployProd
    displayName: Deploy and Publish Stage
    dependsOn: Release
    condition: succeeded('Release')
    jobs:
#      - deployment: DeploymentJob
      - job: DeployJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/develop-prod.yml
        steps:
          - template: jobs/deploy.yml
#        environment: prod
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
