## Starter pipeline
## Start with a minimal pipeline that you can customize to build and deploy your code.
## Add steps that build, run tests, deploy, and more:
## https://aka.ms/yaml
##
##trigger:
##  batch: true
##  branches:
##    include:
##      - develop
#
#
#pr:
#  branches:
#    include:
#      - main
##  paths:
##    exclude:
##      - version.sbt
#variables:
#  - name: vmImage
#    value: 'ubuntu-latest'
#
#stages:
#  - stage: Validate
#    displayName: Release Stage
#    jobs:
#      - deployment: ValidateJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-release.yml
#        environment: UT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/validate.yml
#
#  - stage: UTStage
#    displayName: Deploy UT Stage
#    dependsOn: Validate
#    condition: succeeded('Validate')
#    jobs:
#      - deployment: DeploymentJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-ut.yml
#        environment: UT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
#
#  - stage: UATStage
#    displayName: Deploy UAT Stage
#    dependsOn: UTStage
#    condition: succeeded('UTStage')
#    jobs:
#      - deployment: DeploymentUATJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-uat.yml
#        environment: UAT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
#
#  - stage: ProdStage
#    displayName: Deploy Prod Stage
#    dependsOn: UATStage
#    condition: succeeded('UATStage')
#    jobs:
#      - deployment: DeploymentPRODJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/var-deploy-prod.yml
#        environment: PROD
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy-prod.yml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
  - main

variables:
  - name: vmImage
    value: 'ubuntu-latest'
pool:
  vmImage: 'ubuntu-latest'
steps:
  - checkout: self
    persistCredentials: true
  - powershell: |
      $destinationFolder = $HOME+"\.sbt"
      if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
      New-Item $HOME/.sbt/.credentials -ItemType file
      Add-Content  $HOME/.sbt/.credentials "`nrealm="
      Add-Content  $HOME/.sbt/.credentials "`nhost=bizonedev.pkgs.visualstudio.com"
      Add-Content  $HOME/.sbt/.credentials "`nuser=BizOneDev"
      Add-Content  $HOME/.sbt/.credentials "`npassword=jui7qhnuyl5nnjnvbxd2mnbgp6lytfud375uabgwdizdqt4dfg5a"
  - script: sbt clean
    displayName: 'Running $ sbt clean'
  - script: sbt dev:assembly publish
    displayName: 'Run $ sbt tran sformation/assembly transformation/publish'
