# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pr:
  branches:
    include:
      - dev

variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImage)
        steps:
          - template: jobs/build.yml

#  - stage: Prod
#    displayName: Deploy prod stage
#    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#    jobs:
#      - deployment: DeploymentJob2
#        pool:
#          vmImage: $(vmImage)
#        environment: prod
##        variables:
##          - template: Variables/prod.yml
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml