# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sbt compile
  displayName: 'Running $ sbt clean'
- script: sbt coverageReport
  displayName: 'Running $ sbt coverageReport'
- script: sbt prod:assembly
  displayName: 'Run $ sbt build package jar'
- script: java -cp /home/vsts/work/1/s/target/scala-2.12/prod.jar com.bizone.App
  displayName: 'Run $ job'
