# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- release/*

pool:
  vmImage: ubuntu-latest

steps:
- powershell: |
    New-Item "$HOME/.sbt/.credentials"
    Add-Content  "$HOME/.sbt/.credentials" "`nrealm=https://pkgsprodsu3weu.app.pkgs.visualstudio.com/"
    Add-Content  "$HOME/.sbt/.credentials" "`nhost=bizonedev.pkgs.visualstudio.com"
    Add-Content  "$HOME/.sbt/.credentials" "`npassword=BizOneDev"
    Add-Content  "$HOME/.sbt/.credentials" "`nrealm=hjgonlgdt37jyhaf6hhrydvqft5qoxjbzfmga7rry5sv52m725vq"
- script: sbt clean
  displayName: 'Running $ sbt clean'
#- script: sbt coverage test coverageReport
#  displayName: 'Running $ scan line of code function coverageReport'
- script: sbt coverageOff dev:assembly -Dsbt.gigahorse=false publish
  displayName: 'Run $ sbt coverageOff dev:assembly publish'
- script: java -cp  /home/vsts/work/1/s/target/scala-2.12/sbt-1.0/velocitysbt_2.12-0.0.1-SNAPSHOT.jar com.bizone.App
  displayName: 'Run $ job'
