# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pr:
  branches:
    include:
      - main
      - dev

variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    condition: in(variables['build.sourceBranch'], 'refs/heads/dev')
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImage)
        steps:
          - template: jobs/build.yml

  - stage: Prod
    displayName: Deploy Dev Jar and publish artifact
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeploymentJob2
        pool:
          vmImage: $(vmImage)
        environment: prod
#        variables:
#          - template: Variables/prod.yml
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy.yml