# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main
#      - dev

pr:
  branches:
    include:
      - main
#      - dev

variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Release
    displayName: Release Stage
#    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/dev'))
    jobs:
      - job: ReleaseJob
        pool:
          vmImage: $(vmImage)
        steps:
          - template: jobs/release.yml

  - stage: Deploy
    displayName: compile jar file and publish artifact
    condition: succeeded()
    jobs:
      - job: DeployJob
        pool:
          vmImage: $(vmImage)
        steps:
          - template: jobs/deploy.yml
