# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - dev
      - release
      - main


#pr:
#  branches:
#    include:
#      - dev
#  paths:
#    exclude:
#      - version.sbt
variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
#  - stage: Release
#    displayName: Release Stage
#    jobs:
#      - job: ReleaseJob
#        pool:
#          vmImage: $(vmImage)
#        condition: succeeded('Release'), run dev
#        variables:
#          - template: variables/release.yml
#        steps:
#          - template: jobs/release.yml
#
#  - stage: RollBackRelease
#    displayName: RollBack Release Stage
#    dependsOn: Release
#    condition: failed('Release')
#    jobs:
#      - job: RollBackReleaseJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/release.yml
#        steps:
#          - template: jobs/rollback.yml

  - stage: ReleaseSgtProd
    displayName: Deploy and Publish Stage
#    dependsOn: Release
#    condition: succeeded('Release'), run release, user_approved
    jobs:
      - deployment: DeploymentJob
#      - job: DeployJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/deploy-prod.yml
#        steps:
#          - template: jobs/deploy.yml
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy.yml
#  - stage: ITStage
#    displayName: Deploy and Publish Stage
#    dependsOn: ReleaseSgtProd
#    condition: succeeded('ReleaseSgtProd')
#    jobs:
#      - deployment: DeploymentJob
#        #      - job: DeployJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/deploy-prod.yml
#        #        steps:
#        #          - template: jobs/deploy.yml
#        environment: IT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml
#                    -
#  - stage: UATStage
#    displayName: Deploy and Publish Stage
#    dependsOn: ITStage
#    condition: succeeded('ITStage')
#    jobs:
#      - deployment: DeploymentJob
#        #      - job: DeployJob
#        pool:
#          vmImage: $(vmImage)
#        variables:
#          - template: variables/deploy-prod.yml
#        #        steps:
#        #          - template: jobs/deploy.yml
#        environment: UAT
#        strategy:
#          runOnce:
#            deploy:
#              steps:
#                - template: jobs/deploy.yml