# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
#- script: git push origin HEAD
- checkout: self
  persistCredentials: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "duc.nguyen@bizone.com.vn"
      git config --global user.name "ducnguyen452021"
      git checkout origin/dev
      git commit -m 'build_release_commit'
      git push origin dev
- script: sbt "release release-version 0.1.5 next-version 0.1.6 with-defaults"
  displayName: 'Running $ sbt release release-version 0.1.5 with-defaults'
