# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- script: sbt "release release-version 0.1.5 with-defaults"
  displayName: 'Running $ sbt release release-version 0.1.5 with-defaults'
