# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- powershell: |
    git config --global user.email "matterduc@gmail.com"
    git config --global user.name "matterduc"
    git add -A
    git commit -m 'clone_pipeline'
    git push origin develop
- script: sbt release release-version 0.1.5 with-defaults
  displayName: 'Running $ sbt release release-version 0.1.5 with-defaults'
